# Generated by Django 4.1.7 on 2023-02-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='wachlist',
            new_name='watchlist',
        ),
    ]
